### ISSUE TITLE
We start to work on issues from August - Have a great summer time!

### ISSUE THREAD

**Issue by biancode** [biancode/node-red-iiot-opcua-publicbeta#1]
We start to work on issues from August - Have a great summer time!
We start to work on issues from August - Have a great summer time!
We start to work on issues from August - Have a great summer time!

**Comment by TiptoeOkin** [comment]
Hi Klaus
I've seen you have a lot of projects bringing opc-ua to node red.
I am a little confused, what is the difference between all those.
Which one is going to continue?  Is there a clean version that doesn't come with example nodes but just the one used for the model?
regards

**Comment by biancode** [comment]
@TiptoeOkin please read the README [node-red-contrib-iiot-opcua](https://www.npmjs.com/package/node-red-contrib-iiot-opcua)

**Comment by biancode** [comment]
That is a whole new Node-RED package based on the node-opcua examples and the API documentation. The old copyrights by Mika Karaila are just to honor his pioneer work in the years 2015/2016 for Node-RED and OPC UA.
