### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by fabianyvidal** [biancode/node-red-iiot-opcua-publicbeta#3]
I have  tried to install iiot opc Ua  following the instructions ,but I always get the same error:

 Local gulp not found in d:\node-red-0.17.5\node_modules\.staging\node-red-contrib-iiot-opcua-e46790ee.

I tryied installing gulp but the error was not solved.

this is what i tried;

C:\Users\fabian.vidal\.node-red  (node-red-project@0.0.1)
λ npm install node-red-contrib-iiot-opcua --unsafe-perm --build-from-source

> node-red-contrib-iiot-opcua@1.0.4 preinstall C:\Users\fabian.vidal\.node-red\node_modules\.staging\node-red-contrib-iiot-opcua-4a7e544c
> standard --fix && npm run build && npm test

> node-red-contrib-iiot-opcua@1.0.4 build C:\Users\fabian.vidal\.node-red\node_modules\.staging\node-red-contrib-iiot-opcua-4a7e544c
> standard --fix && gulp clean && gulp publish

[21:45:24] Local gulp not found in ~\.node-red\node_modules\.staging\node-red-contrib-iiot-opcua-4a7e544c
[21:45:24] Try running: npm install gulp

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! node-red-contrib-iiot-opcua@1.0.4 build: `standard --fix && gulp clean && gulp publish`
npm ERR! Exit status 1

**Comment by biancode** [comment]
please, try first

`npm i -g gulp-cli`

if not install also

`npm i -g gulp`

and please let me know if gulp-cli is enough

**Comment by biancode** [comment]
fixed in v1.0.5

**Comment by fabianyvidal** [comment]
That was great!!, it worked , now i have  iiot opc ua in my node red.

 thank you!!!

**Comment by biancode** [comment]
great, have fun!
