### ISSUE TITLE
installation failed don't have -rand option in openssl

### ISSUE THREAD

**Issue by giminni** [biancode/node-red-iiot-opcua-publicbeta#5]
I tried to install node-red-iiot-opcua under Docker and Alpine Linux.
Alpine Linux uses libreSSL and there is no -rand option available.

Therefore the installation was partial successful, because could not build the 
needed certificates due to the lack of -rand in openssl.

The connection to an OPC/UA server will fail later due to the lack of certificates.

Can the certificate be build without using a random file?

> OpenSSL version :  LibreSSL 2.6.3
 ########################################### OPENSSL ERROR  ###############################
Command failed: "openssl" genrsa  -out "/usr/src/node-red/node_modules/node-opcua-client/certificates/PKI/own/private/private_key.pem" -rand "/usr/src/node-red/node_modules/node-opcua-client/certificates/PKI/own/private/random.rnd" 2048
usage: genrsa [args] [numbits]
 -des            encrypt the generated key with DES in cbc mode
 -des3           encrypt the generated key with DES in ede cbc mode (168 bit key)
 -idea           encrypt the generated key with IDEA in cbc mode
 -aes128, -aes192, -aes256
                 encrypt PEM output with cbc aes
 -camellia128, -camellia192, -camellia256
                 encrypt PEM output with cbc camellia
 -out file       output the key to 'file
 -passout arg    output file pass phrase source
 -f4             use F4 (0x10001) for the E value
 -3              use 3 for the E value

 ########################################### OPENSSL ERROR  ###############################

**Comment by biancode** [comment]
Dear Giovanni,

that is an issue for [node-opcua](https://github.com/node-opcua/node-opcua/issues), please.
node-opcua-client problem
